apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      imagePullSecrets:
      - name: gcrsecret
      containers:
        - name: api
          image: {{ .Values.image }}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.secrets.PORT }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.secrets.PORT }}
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.secrets.PORT }}
            periodSeconds: 5
          env:
            {{- range $key, $value := .Values.secrets }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}