apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    name: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.secrets.PORT }}
      targetPort: {{ .Values.secrets.PORT }}