apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-notifications-secret
  namespace: argocd
data:
  webhook-url: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: "https://example.com"
  service.webhook.discord: |
    url: $webhook-url
    headers:
    - name: "Content-Type"
      value: "application/json"
  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "content": "",
            "tts": false,
            "embeds": [
              {
                "id": 652627557,
                "title": "Sync succeeded",
                "description": "The application **{{.app.metadata.name}}** has synced successfully!",
                "color": 65344,
                "fields": [],
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
              }
            ],
            "components": [],
            "actions": {}
          }
  template.app-health-missing: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "content": "",
            "tts": false,
            "embeds": [
              {
                "id": 652627557,
                "title": "Health missing",
                "description": "The application **{{.app.metadata.name}}** has a missing health!",
                "color": 16424192,
                "fields": [],
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
              }
            ],
            "components": [],
            "actions": {}
          }
  template.app-health-degraded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "content": "",
            "tts": false,
            "embeds": [
              {
                "id": 652627557,
                "title": "Health degraded",
                "description": "The application **{{.app.metadata.name}}** has a degraded health!",
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": 16384000,
                "fields": []
              }
            ],
            "components": [],
            "actions": {}
          }
  trigger.on-health-missing: |
    - when: app.status.health.status == 'Missing'
      send: [app-health-missing]
  trigger.on-health-degraded: |
    - when: app.status.health.status === 'Degraded'
      send: [app-health-degraded]
  trigger.on-sync-succeeded: |
    - when: app.status.sync.status === 'Succeeded'
      send: [app-sync-succeeded]